packages/coin-bnb/src/utils/scriptUtil.ts
- Change bnb place order `orderAddress` encode from `ascii` to `hex`.
=> fix(bnb): change bnb place order orderAddress encode from `ascii` to `hex`

packages/coin-tester/vite.config.ts
Package `@coolwallet/xml` use `stellar-sdk` which is using `es6-promise`.
`es6-promise` inline require `vertx` package. 
If `vite-common-js` will transform all inline require to global require , it will cause some issues.
https://github.com/originjs/vite-plugins/issues/17
=> fix(coin-tester): viteCommonjs should skipPreBuild

packages/core/package-lock.json, packages/core/package.json, packages/core/src/config/index.ts
Both android JSC and [facebook/Hermes](https://github.com/facebook/hermes) do not support native BigInt.
@noble-secp256k1 is built with native BigInt, so we need to remove it.
=> fix(core): remove native bigInt library

packages/coin-etc/src/index.ts
`getFullPath` should use addressIndex variable instead of zero.
=> fix(etc): ETC addressIndex should be dynamic

packages/coin-matic/src/utils/polygonUtils.ts
Should not reverse buffer when composing signature.
=> fix(matic): should compose correct signature

packages/coin-tester/src/components/settings.tsx, packages/core/package-lock.json, packages/core/package.json, packages/core/src/apdu/transaction.ts, packages/core/src/config/status/msg.ts
- Add create wallet without Cardano seed in `coin-tester`.
- Add `6D64` error message.
- Add `getExplicitTxDetail` to get txDetail string.
=> feat(core): add getExplicitTxDetail

packages/core/package-lock.json, packages/core/package.json, packages/core/src/apdu/transaction.ts
P1 and P2 should only contain single-byte information which is not allowed to be greater than 'ff'.
If the argument is too long, it might increase P1 and P2 to two bytes which will cause an APDU command syntax error.
This patch will re-iterate the loop if P1 or P2 is greater than 'ff'.
=> fix(core): executeSegmentScript overflow issue

packages/coin-xtz/src/config/tokenType.ts
Due to the official Tezos tokens are currently undecided. Thus, commented out the token that was used in testing and replace the essential data as 'Temp'.
=> feat(Tezos): Comment out token

packages/coin-avaxc/package.json, packages/coin-avaxc/src/index.ts, packages/coin-bsc/package.json, packages/coin-bsc/src/sign.ts, packages/coin-cronos/package.json, packages/coin-cronos/src/sign.ts, packages/coin-eth/package.json, packages/coin-eth/src/sign.ts, packages/coin-evm/package.json, packages/coin-evm/src/index.ts, packages/coin-matic/package.json, packages/coin-matic/src/sign.ts
When using hermes, the App will encounter error: Maximum call stack size exceeded.
Refer https://github.com/ajv-validator/ajv/issues/1581#issuecomment-835774241 to resolve this problem
I have tested `@coolwallet/evm` on coin-tester. The `signTypedData` function of it works fine.
=> 🐛 [CW-13609] fix: react native hermes error by stack size error from ajv module

packages/coin-bnb/package.json
PR: https://github.com/CoolBitX-Technology/coolwallet-sdk/pull/661  is not published because remote module version have been published with v1.1.3
=> 🔖 [CW-19344] chore: publish coin-bnb 1.1.4

packages/coin-sol/src/utils/stringUtil.ts
----
Changes:
To revise the logic of isBase58Format to prevent issues with Blob encoding encountered by signTransaction.
*Checklist:*
=> [CW-20067] fix(sol): Change isBase58Format check pattern

packages/coin-sol/package.json, packages/coin-sol/src/message/legacy.ts, packages/coin-sol/src/sign.ts
----
*Testing Result:* passed
```
const rawTx = 
'01000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100010246a448fb09aea355ea540c1e2e86127d4795a86a533a977e20f5476f5bd100a5054a535a992921064d24e87160da387c7c35b5ddbc92bb81e41fa8404105448d46f62fe8ed25e2ed67188596d19735fc0679d8c917d1589ea412d5b97f145b7d0101003248656c6c6f2c2066726f6d2074686520536f6c616e612057616c6c65742041646170746572206578616d706c652061707021'
const versionedTransaction:VersionedTransaction =  
VersionedTransaction.deserialize(new Uint8Array(Buffer.from(rawTx,'hex')))
const signData = {
addressIndex: 0, 
transaction: versionedTransaction,
transport: {} as any,
appPrivateKey: 'abc',
appId: '123',
confirmCB(): void {
// Method is intentionally left …
```
=> fix: Modified Message.from() for accurate transaction message serialization

packages/coin-sol/package-lock.json, packages/coin-sol/package.json, packages/coin-sol/src/utils/scriptUtil.ts
- **fix: 6ae2 if user is sending token which symbol length is greater than 7**
- **chore: execute 'npm install'**
=> 🐛 fix: user cannot send SPL token if its symbol length is greater than 7

packages/transport-jre-http/package-lock.json, packages/transport-jre-http/package.json, packages/transport-jre-http/src/index.ts, packages/transport-jre-http/src/transport.ts
- **feat: migrate to implement Transport interface instread of extending class**
- **chore(jre-http): update version to 2.0.0-beta.1**
=> chore(transport-jre-http): migrate to implement Transport interface instead of extending class

packages/transport-react-native-nfc/package-lock.json, packages/transport-react-native-nfc/package.json, packages/transport-react-native-nfc/src/utils.ts
support nfc transceive data more then 251 bytes.
=> feat(transport-react-native-nfc): support nfc transceive data more then 251 bytes

packages/coin-sol/package-lock.json, packages/coin-sol/package.json, packages/coin-sol/src/utils/stringUtil.ts
```
/**
* CW-21334 Fixed user's publicKey just matches the base58 encoding, resulting in repeated decoding.
*
* The user's Solana address (base58 encoded) is:
* 5XZiuCyozesbRJsSdoJQCTHQRnTGDfSms5bV1ybLn9yg
*
* After converting it to Hex:
* fc238b62abd32cd576f1d5568d3b6b5cb2fbc57b419cc2b4cd8a2814973919a7
* This hex conform to the Base58 format (without 0, O, i, I, +, /), causing base58.decode to be executed again, resulting in an incorrect publicKey. 
*
* How to fix it:
* Adjust base58 verification method. A 32-byte public key can only be base58 encoded using 43 or 44 characters.
*/
```
=> fix(SOL):  solana sending failure because publicKey matches base58

package-lock.json, scripts/install-test-fixture.sh
Before running unit test. You can run `sh ./scripts/install-test-fixture.sh` at project root to prepare test fixture
=> 🔨 chore: add script to install test fixture

README.md
------------
**Summary:**
- Updated `@coolwallet/kas` package README.md to change the coin icon name from "Icon" to "Kaspa".
**Key points:**
- Modified the README.md file.
- Changed the coin name for `@coolwallet/kas` package.
**Changes:**
1. **README.md:**
- Updated the coin name for `@coolwallet/kas` in the list of packages.
**Impact:**
- The visual representation of the `@coolwallet/kas` package in various platforms will now display "Kaspa" instead of "Icon".
**Tools:**
- README.md file editor.
=> fix(kas): 修正 readme 中的 name

packages/coin-evm/package-lock.json, packages/coin-evm/package.json
- move web3-utils from devDependencies to dependencies to fix evm token connot transfer issue
- 有 local 測試過 Polygon, Polygon USDT, Arbitrum USDT 都可以正常發送
----
*Checklist:*
------------
**Summary:**
This pull request updates package versions and checksums for `@coolwallet/core` and several dependencies. Some dependencies have the `dev` flag removed.
1. Updates package versions and checksums for `@coolwallet/core` and dependencies.
2. Removes `dev` flag for certain dependencies.
3. Affects multiple projects, including `coin-evm`.
4. Updates `utf8`, `util-deprecate`, and `web3-utils` packages for `coin-evm`.
5. Removes …
=> [CW-21695] 🐛  fix: move web3-utils from devDependencies to dependencies to fix evm token connot transfer issue

packages/coin-bsc/tsconfig.json
------------
**Summary**
Updated `tsconfig.json` in `coin-bsc` to include all `src` files for TypeScript compilation.
**Key Points**
1. Expanded `tsconfig.json` coverage in `coin-bsc`.
2. Included all `src` files for TypeScript compilation.
3. Previous configuration only had basic options. 
=> 💚 fix(bsc): publish failed by `npm run build`

packages/transport-react-native-nfc/package-lock.json, packages/transport-react-native-nfc/package.json, packages/transport-react-native-nfc/src/utils.ts
in generally, apdu command can bring 3 bytes to describe data length, please refer to: [apdu lc](https://zh.wikipedia.org/zh-tw/%E6%99%BA%E8%83%BD%E5%8D%A1%E5%BA%94%E7%94%A8%E5%8D%8F%E8%AE%AE%E6%95%B0%E6%8D%AE%E5%8D%95%E5%85%83#:~:text=%E8%99%95%E5%AF%AB%E5%85%A5%E6%95%B8%E6%93%9A-,Lc,-0%2C%201%20%E6%88%96)
but do firmware update failed, because our lite card's ssd applet only support 1 bytes data length.
test firmware update on app e2e. ✅
------------
**Summary**
This pull request updates package versions to beta.5 for `@coolwallet/transport-react-native-nfc` and modifies `utils.ts` for APDU command length handling.
**Key Points**
1. Upgrades package versions in `package-lock.json` and `package.json` to beta.5.
2. Modifies `utils.ts` for handling 1 or 3 bytes …
=> 🐛 fix(core): firmware update failed because ssd applet not support 3 bytes data length 

packages/coin-kas/package-lock.json, packages/coin-kas/package.json, packages/coin-kas/src/utils/__test__/address.test.ts, packages/coin-kas/src/utils/address.ts
------------
**Summary**
This pull request updates package versions and adds a new test case (Version update and Testing), modifies a function's return type (Type modification).
**Key Points**
* Updates "@coolwallet/kas" package versions in package-lock.json and package.json
* Adds a test case in address.test.ts to validate address decoding
* Modifies a function's return type from Buffer object to Buffer variable `hashOrPublicKeyBuffer` 
=> feat(coin-kas): check pubkey is correct in decodeAddress

packages/transport-react-native-nfc/package-lock.json, packages/transport-react-native-nfc/package.json, packages/transport-react-native-nfc/src/transport.ts
----
*Checklist:*
------------
**Summary**
This pull request updates package versions and adds error listener functionality to `NFCTransport` class.
**Key Points**
* Updates package versions in `package-lock.json` and `package.json` to `beta.6`.
* Adds error listener to `NFCTransport` class for registering and removing error callbacks. 
=> feat(transport): add error handler in NFCTransport

packages/core/package-lock.json, packages/core/package.json, packages/core/src/crypto/signature.ts
------------
**Summary**
This pull request updates package versions to `1.1.30-beta.0` and pads signature strings in `getCanonicalSignature` function.
**Key Points**
* Updates package versions to `1.1.30-beta.0` in `package-lock.json` and `package.json`.
* Pads `canonicalS` and `canonicalR` strings in `getCanonicalSignature` to 64 characters long. 
=> fix(core): CW-22295 length of s in canonical signature must be 32 bytes

packages/coin-dot/package-lock.json, packages/coin-dot/package.json, packages/coin-dot/src/utils/transactionUtil.ts, packages/coin-eth/tests/index.spec.ts, packages/core/src/transaction/txUtil.ts
此 pr 主要更新 core 版本，並且修正 dot 在組交易時使用 s32 來組，避免交易遇到 bad signature 導致交易失敗
*Checklist:*
------------
**Summary:**
This pull request includes updates to package versions, mnemonic phrase, and signature decryption in the Eth SDK.
1. Fixed mnemonic phrase in Eth SDK tests.
2. Added `s32` value when decrypting signature from SE in `txUtil.ts`.
3. Updated packages and dependencies, including "@coolwallet/core", "@types/bn.js", "jose", "types/bluebird", and "js-sha3". 
=> 🐛  [CW-22295] fix: dot test failed

.github/workflows/auto_test.yml, .github/workflows/test-and-generate-report.yml
add Set up Cloud SDK to fix gcloud command not found error
https://github.com/CoolBitX-Technology/coolwallet-sdk/actions/runs/11284557686/job/31385934383
有試過增加 `Set up Cloud SDK `後，可正常執行 gcloud
https://github.com/CoolBitX-Technology/coolwallet-sdk/actions/runs/11287210006
----
*Checklist:*
=> 🐛 fix: gcloud not found error

packages/core/package-lock.json, packages/core/package.json
`@coolwallet/core` had been used on CoolWallet App production.
------------
**Summary**
Updated "@coolwallet/core" package version from beta to stable in package-lock.json and package.json.
**Key Points**
* Changed "@coolwallet/core" version from "1.1.30-beta.1" to "1.1.30"
* Updated package-lock.json and package.json accordingly. 
=> ⬆️ chore(core): update core to 1.1.30 from beta

packages/coin-trx/package-lock.json, packages/coin-trx/package.json, packages/coin-trx/src/config/tokenType.ts
local build 驗證：
1. 確認 App 加幣頁已移除 TRX USDC✅
2. 確認發送 TRX USDC 卡片出現三條線([tx](https://tronscan.org/#/transaction/b714421afb477f027381084a936bd1713e0a2bc807d2b7c3956ab9a9d713e4a2))✅
*Checklist:*
------------
**Summary:**
Upgrades "@coolwallet/trx" package to version "1.1.7" and removes an outdated token configuration.
1. Updates package versions in `package-lock.json` and `package.json`.
2. Removes outdated token configuration from `src/config/tokenType.ts`. 
=> ✨ [CW-20101] feat: remove trx usdc from official token

packages/coin-bch/__tests__/index.spec.ts, packages/coin-bch/package-lock.json, packages/coin-bch/package.json, packages/coin-bch/src/index.ts, packages/coin-bch/src/utils/scriptUtil.ts, packages/coin-bch/tsconfig.json, scripts/run-all-test-report.sh
- **test: add test case - `BCH test get address 0`**
- **test: add BCH signTransaction test case**
- **feat: add ScriptType type**
------------
**Summary:**
This pull request introduces new tests for the BCH SDK and updates the Jest configuration in the `coin-bch` package.
1. Adds tests for getting an address and signing a transaction in `index.spec.ts`.
2. Introduces two new tests for the `signTransaction` function in the Bitcoin Cash library.
3. Updates Jest configuration with new options in `package.json`.
4. Changes `ScriptType` definition in `BCH` class and updates `tsconfig.json`.
5. Adds new test scope "@coolwallet/bch" to the existing list in the "run-all-test-report.sh" script. 
<h6>To turn off PR summary, please visit <a …
=> fix(bch): [CW-22894] cannot send to specfic address that starts with 3

packages/core/package-lock.json, packages/core/package.json, packages/core/src/bip66.d.ts, packages/core/src/crypto/signature.ts
correct bip66.encode type from any to Buffer
------------
**Summary**
This pull request updates package versions and modifies a function return type.
* Updates "@coolwallet/core" version in package-lock.json and package.json
* Changes "convertToDER" function return type in signature.ts from object to Buffer. 
=> fix(core): correct bip66.encode type to Buffer

packages/core/CHANGELOG.md, packages/core/package-lock.json, packages/core/package.json, packages/core/src/apdu/index.ts, packages/core/src/apdu/ota/api.ts, packages/core/src/apdu/ota/index.ts, packages/core/src/apdu/ota/ota.ts
------------
**Summary:**
This pull request introduces version 1.2.0-beta.0 of @coolwallet/core with a breaking change in `updateSE` function's parameter and removal of the OTA api secret. It also refactors `updateSE` and introduces a new interface `UpdateSeParams`.
1. Introduces new version with breaking change and dependency updates.
2. Refactors `updateSE` function with new interface and optional `apiSecret` parameter.
3. Updates `getAPIOption` function to accept optional `apiSecret` parameter. 
=> chore: remove OTA api secret

packages/coin-atom/package-lock.json, packages/coin-atom/package.json, packages/coin-atom/src/config/types.ts, packages/coin-atom/src/index.ts
I've tested locally that types can import from index
------------
**Summary:**
This pull request updates package versions and introduces new interfaces.
- Upgrades packages to versions `1.1.4`.
- Introduces `MsgUndelegate` and `MsgWithdrawDelegationReward` interfaces.
- Exports new interfaces, along with other types and classes. 
=> ✨ feat(atom): export types from index so that client can import type from index

packages/coin-xrp/package-lock.json, packages/coin-xrp/package.json
------------
**Overview**
This PR corrects an issue with the XRP package version in `package.json` and `package-lock.json`. The incorrect caret (`^`) was causing an unintended version mismatch during publishing.
- Removed the caret (`^`) from the version string in both `package.json` and `package-lock.json`, fixing the version to `2.0.0-beta.0`.
Ready to merge. This is a small but important fix to ensure the correct XRP package version is published.
=> fix(xrp): wrong version publish

packages/coin-xrp/tests/index.spec.ts
------------
**Overview**
This PR fixes a deployment failure issue in the `coin-xrp` package caused by incorrect import paths during testing.
- Corrected the import path of the `XRP` module in the `index.spec.ts` test file from `../index` to `../src/index`.  This change ensures the correct module is used during testing and deployment.
Ready to merge after verifying that the unit tests pass and the deployment process completes successfully.
=> fix(xrp): 修正因為跑到測試導致部署失敗問題

packages/coin-kas/package-lock.json, packages/coin-kas/package.json, packages/coin-kas/src/index.ts, packages/coin-kas/src/sign.ts, packages/coin-kas/src/utils/scriptUtil.ts
------------
**Overview**
This PR updates the `@coolwallet/kas` package to support CoolWallet Lite. It bumps the package version to `2.0.0-beta.0` and updates the `@coolwallet/core` dependency to `2.0.0-beta.19`.  The PR also modifies the transaction signing process and exports `ScriptType`.
- Updated `@coolwallet/core` dependency to `2.0.0-beta.19`.
- Changed `apdu.tx.*` calls to `tx.command.*` for CoolWallet Lite compatibility.
- Exported `ScriptType` for external use.
- Modified type imports and usage to avoid potential conflicts.
- Updated package version to `2.0.0-beta.0`.
Ready for merge after testing the KAS SDK with CoolWallet Lite to ensure all functionalities work as expected, especially the transaction signing process. …
=> [CW-21906] feat(kas): support on lite

packages/core/package-lock.json, packages/core/package.json, packages/core/src/utils/index.ts
----
*Checklist:*
------------
**Overview**
This PR adds support for creating Cardano seeds on CoolWallet Go devices.  The core library version is bumped to 2.0.0-beta.20.
- Updated the `createWalletByMnemonic` function to conditionally create Cardano master keys based on the CoolWallet version and type (Pro or Lite).  CoolWallet Pro requires version 317 or higher.
- Updated package version to 2.0.0-beta.20.
Not deployment ready.  While the changes seem targeted, more information is needed to assess production readiness. Please provide details on testing performed, especially integration tests …
=> feat(core): support creating cardano seed on coolwallet go

packages/coin-zen/package-lock.json, packages/coin-zen/package.json, packages/coin-zen/src/index.ts
------------
**Overview**
This PR updates the `@coolwallet/zen` package to version 2.0.0-beta.1. It introduces the export of `ScriptType` and renames the default export class from `BTC` to `ZEN`.  It also adds a synchronous method `getAddressAndOutScriptByAccountKeySync`.
- Package version bumped to 2.0.0-beta.1.
- `ScriptType` from `./config/types` is now exported.
- Default export class renamed from `BTC` to `ZEN`.
- New synchronous method `getAddressAndOutScriptByAccountKeySync` added.
- Asynchronous `getAddressAndOutScriptByAccountKey` now uses the synchronous method internally.
Not deployment ready. While the changes seem minor, the lack of explanation for the renaming and the addition of the synchronous method raises …
=> feat(zen): export script type from zen

packages/coin-cro/package-lock.json, packages/coin-cro/package.json, packages/coin-cro/src/sign.ts
----
*Checklist:*
------------
**Overview**
This PR removes the `getSignedHex` function call and associated logging within the `signTransaction` function in `sign.ts`.  It also bumps the package version from `2.0.0-beta.0` to `2.0.0-beta.1`.
- Removed `getSignedHex` function call.
- Removed console logging of `signedTx`.
- Updated package version.
Not deployment ready. While the removal of the logging statement is a positive change, the removal of `getSignedHex` without explanation raises concerns.  The PR needs more context explaining why this function is no longer necessary and what impact its …
=> feat(Crypto.org): remove getSignedHex

packages/transport-react-native-nfc/package-lock.json, packages/transport-react-native-nfc/package.json, packages/transport-react-native-nfc/src/transport.ts
- **chore: add nfc transport log**
- **chore(transport-react-native-nfc): bump version to 1.0.0-beta.8**
------------
**Overview:**
This PR adds logging for APDU requests and responses in the `NFCTransport` class within the `transport-react-native-nfc` package. This enhancement aims to improve debugging and monitoring capabilities.  It also increments the package version.
- Added `console.log` statements to display the APDU command, packets, response length, response in hex format, and time taken for each request.
- Incremented package version from `1.0.0-beta.7` to `1.0.0-beta.8`.
Not deployment ready. While the added logging is helpful for debugging, consider using a dedicated logging library instead of `console.log` for …
=> feat(nfc-transport): add APDU request and response logs

packages/core/src/apdu/ota/ota.ts
------------
**Overview**
This PR modifies the OTA update process to always attempt to back up registration data, even if the card isn't recognized by the device.  It also adds more robust logging and conditional backup recovery.
- Removed the card recognition check (`isCardRecognized`) before backing up registration data.
- Backup register data now occurs if the wallet is created and recovery is needed.
- Added `try-catch` blocks and logging for `deleteBackupRegisterData` and `backupRegisterData` operations.
Not deployment ready.  While the change addresses a potential data loss scenario, removing the card recognition check might have unintended consequences.  Consider adding a check for a valid card session or other criteria to …
=> chore: CW-24146 do backup register data event if card is not recognized

packages/core/CHANGELOG.md, packages/core/package-lock.json, packages/core/package.json
------------
**Overview**
This PR bumps the version of `@coolwallet/core` from `2.0.1-beta.2` to `2.0.1`. It includes a fix for creating wallets from seed (Go SE 13).
- Updated the version number in `package.json` and `package-lock.json`.
- Added a changelog entry for the bug fix.
Ready for deployment. This is a minor version bump with a bug fix, so it's unlikely to introduce breaking changes.
| Category    | Lines Changed |
|-------------|---------------|
| New Work    | 1 (20%)      |
| Rework      | 4 (80%)      |
| Total Changes | 5           |
<h6>To turn off PR summary, please visit <a href="https://app.typoapp.io/settings/notification?tab=codeHealth">Notification settings</a>.</h6>
=> chore(core): bump @coolwallet/core to v2.0.1

packages/coin-evm/package-lock.json, packages/coin-evm/package.json, packages/coin-evm/src/utils/signature.ts
------------
**Overview:**
This PR updates the `@coolwallet/evm` package to version 2.0.1-beta.0, bumping the `@coolwallet/core` dependency to 2.0.2-beta.1. It introduces a new function `getRecoveryParam` and modifies `genEthSigFromSESig` to support direct transaction hash signing by adding an `alreadyHash` parameter.
- Updated `@coolwallet/core` dependency to 2.0.2-beta.1.
- Added `getRecoveryParam` function to calculate the recovery parameter directly from a data hash, canonical signature, and public key.
- Modified `genEthSigFromSESig` to accept an optional `alreadyHash` boolean.  When true, the function skips hashing the payload, allowing direct use of a transaction hash.
Not deployment ready. While the changes seem …
=> feat(evm): genEthSigFromSESig 支援直接還原 txHash

packages/coin-evm/package-lock.json, packages/coin-evm/package.json, packages/coin-evm/src/index.ts
----
*Checklist:*
------------
**Overview**
This PR fixes a type export issue in the `@coolwallet/evm` package, specifically addressing the inability to export types from the `./transaction/types` module.  The fix updates the export statement to correctly export the types.  Additionally, the package version is bumped from `2.0.1-beta.1` to `2.0.1-beta.2`.
- Corrected the type export statement in `index.ts` from `export type *` to `export *`.
- Updated the package version in both `package.json` and `package-lock.json` to `2.0.1-beta.2`.
Ready for deployment. This is a small, targeted fix that …
=> fix(evm): can't export type from @coolwallet/evm

packages/coin-evm/package-lock.json, packages/coin-evm/package.json, packages/core/CHANGELOG.md, packages/core/package-lock.json, packages/core/package.json, packages/testing-library/package-lock.json, packages/testing-library/package.json
------------
**Overview:** This PR bumps the version of `@coolwallet/evm`, `@coolwallet/core`, and `@coolwallet/testing-library` from beta to formal release versions (2.0.1, 2.0.2, and 2.0.0, respectively). The `core` update includes an implementation of `signECDSA` for improved signing speed.
- Updated version numbers in `package.json` and `package-lock.json` for all three packages.
- Added a changelog entry for `@coolwallet/core` detailing the `signECDSA` implementation.
Ready for deployment. This PR represents a standard version bump with a minor performance improvement.
| Category    | Lines Changed |
|-------------|---------------|
| New Work    | 3 (25%)      |
| Rework      | 9 (75%)       |
| Total Changes | 12 …
=> chore: bump evm, core and testing-library to stable version

packages/core/CHANGELOG.md, packages/core/package-lock.json, packages/core/package.json, packages/core/src/transport/index.ts
- **feat: add hooks on BleTransport**
- **chore: bump core to 2.0.2-beta.1**
------------
**Overview:**
This PR adds pre and post request hooks to the `BleTransport` class, allowing for actions to be performed before and after a request to the card.  This update is part of version 2.0.3-beta.1.
- Introduced `onBeforeRequest` and `onAfterRequest` hooks in the `BleTransport` class.
- Updated the `request` method to call these hooks before and after sending APDU commands.
- Updated changelog and package version.
Not deployment ready.  The added hooks have default empty implementations.  Provide clear guidance on intended usage and add examples to ensure proper implementation by consumers of the library.
| Category    | Lines …
=> feat(core): add hooks to BleTransport

packages/core/package-lock.json, packages/core/package.json, packages/core/src/info/index.ts
CardInfo.cardanoSeed has wrong type string, it should be boolean
----
*Checklist:*
------------
**Overview:**
This PR updates the `cardInfo.cardanoSeed` type from string to boolean and renames it to `hasCardanoSeed`. This change improves type safety and clarity by explicitly indicating whether a Cardano seed exists. The version is bumped to 2.0.3-beta.3.
- Changed `cardanoSeed` type from string to boolean in `getCardInfo` response.
- Renamed `cardanoSeed` to `hasCardanoSeed`.
- Updated package version to 2.0.3-beta.3.
Ready for deployment. This is a small, targeted change that improves type …
=> fix(core): update cardInfo.cardanoSeed type from string to boolean @coolwallet/core(2.0.3-beta.3)
