- packages/core/src/apdu/execute/command.ts
- packages/core/src/apdu/execute/execute.ts
- packages/core/src/apdu/general.ts
- packages/core/src/apdu/informational.ts
- packages/core/src/apdu/mcu/control.ts
- packages/core/src/apdu/mcu/dfu.ts
- packages/core/src/apdu/mcu/display.ts
- packages/core/src/apdu/ota.ts
- packages/core/src/apdu/pair.ts
- packages/core/src/apdu/setting.ts
- packages/core/src/apdu/transaction.ts
- packages/core/src/apdu/wallet.ts
- packages/core/src/config/index.ts
- packages/core/src/config/key.ts
- packages/core/src/config/param.ts
- packages/core/src/config/target.ts
feat: CWC-149 add new function getSEPublicKey
>  feat(SDK): CWA-149

- packages/cws-atom/package-lock.json
- packages/cws-atom/package.json
- packages/cws-trx/package-lock.json
- packages/cws-trx/package.json
- packages/cws-trx/src/index.ts
hotfix: fix trx get wrong withdraw script
> hotfix: fix trx get wrong withdraw script

- packages/cws-xlm/src/index.ts
- packages/cws-xlm/src/utils/scriptUtil.ts
feat: Cwc 201 fix xlm slip0010 transaction fail
> fix(xlm): CWC-201 fix xlm slip0010 transaction fail

- packages/core/src/coin/EDDSA.ts
- packages/core/src/config/index.ts
- packages/core/src/config/param.ts
- packages/core/src/utils/index.ts
- packages/cws-xlm/src/config/params.ts
- packages/cws-xlm/src/utils/scriptUtil.ts
xlm: change bip44 prefix 32 for 42, update get address and sign transaction
core: update get path
> feat(xlm): CWC-183 support bip44 address generation

- packages/cws-atom/src/config/types.ts
Fix: change atom chain id 3 for 4
> Fix: change atom chain id 3 for 4

- .github/publish-action/dist/index.js
- .github/publish-action/package-lock.json
- .github/publish-action/utils.ts
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/apdu/ota.ts
- packages/core/src/index.ts
1. fix core package auto build.
2. modify github action behavior to have chance to skip beta version.
> Modify auto deploy on master branch

- packages/coin-bsc/src/index.ts
> feat(token): CWC-315 Add BEP-20 token

- packages/coin-bnb/README.md
- packages/coin-bsc/README.md
- packages/coin-btc/README.md
- packages/coin-eth/README.md
Summary:
Update BNB, BSC, BTC, and ETH README docs.
Changes:
Update descriptions and usages
Add arguments tables and methods' details
> docs(bnb, bsc, btc, eth):cwc-304 update README.ME

- packages/coin-atom/README.md
- packages/coin-bch/README.md
- packages/coin-dot/README.md
- packages/coin-trx/README.md
Summary:
Update BCH, DOT, ATOM, and TRX README docs.
Changes:
Update descriptions and usages
Add arguments tables and methods' details
> docs(bch, dot, atom, trx):cwc-318 update README.ME

- packages/coin-bsc/package-lock.json
- packages/coin-bsc/package.json
- packages/coin-eth/package-lock.json
- packages/coin-eth/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/index.ts
> fix: revise package versions

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/index.ts
> fix: modify dependencies in package.json for type definition

- packages/coin-cro/.babelrc
- packages/coin-cro/package-lock.json
- packages/coin-cro/package.json
- packages/coin-cro/src/config/params.ts
- packages/coin-cro/src/index.ts
- packages/coin-cro/src/utils/ethUtils.ts
- packages/coin-cro/tsconfig.json
- packages/coin-cro/webpack.config.js
- packages/coin-tester/package-lock.json
- packages/coin-tester/package.json
- packages/coin-tester/src/components/coins/coin-cro/index.tsx
- packages/coin-tester/src/components/coins/index.ts
Summary:
Integration of Cronos
Update on coin-tester to test the functionality of getAddress
getAddress success
> feat(cro): CWC-270 Cronos SDK getAddress & coin-tester update

- packages/transport-jre-http/.babelrc
- packages/transport-jre-http/README.md
- packages/transport-jre-http/package-lock.json
- packages/transport-jre-http/package.json
- packages/transport-jre-http/src/configs/commands.ts
- packages/transport-jre-http/src/configs/endpoints.ts
- packages/transport-jre-http/src/index.ts
- packages/transport-jre-http/src/services/http.ts
- packages/transport-jre-http/src/utils.ts
- packages/transport-jre-http/tests/transport.spec.ts
- packages/transport-jre-http/tsconfig.json
Create a new package `transport-jre-http` which is responsible for communicating between JCVM and SDK.
> feat(transport/transport-jre-http): CWC-369 create JCVM transport

- packages/coin-eth/package.json
- packages/coin-eth/src/utils/ethUtilsEIP1559.ts
- packages/coin-matic/package.json
> feat(coin-eth): CW-6231 Fix EIP1559 issue

- .github/publish-action/dist/index.js
- .github/publish-action/index.ts
- packages/transport-jre-http/package-lock.json
- packages/transport-jre-http/package.json
- packages/transport-jre-http/src/transport.ts
To write some tests, it has needed to release this package to the npm registry.
> chore(*): release transport-jre-http 1.1.2

- packages/coin-etc/package.json
- packages/coin-etc/src/index.ts
- packages/coin-etc/src/utils.ts
- Signing ETC normal transfer script.
> fix(etc): signing etc script

- packages/coin-matic/package-lock.json
- packages/coin-matic/package.json
- packages/coin-matic/src/config/types.ts
- packages/coin-matic/src/index.ts
- packages/coin-matic/src/sign.ts
- packages/coin-matic/src/utils/polygonUtils.ts
- packages/coin-matic/src/utils/scriptUtils.ts
- packages/coin-matic/src/utils/scriptUtilsEIP1559.ts
- packages/coin-tester/src/components/coins/matic/index.tsx
- Remove property `chainId` from the transaction
- Refactor some code in `coin-matic`
- Make `coin-tester/matic` more convenient
> feat(polygon): remove dynamic chainId from transaction

- .github/publish-action/dist/index.js
- .github/publish-action/index.ts
- packages/testing-library/.babelrc
- packages/testing-library/README.md
- packages/testing-library/package-lock.json
- packages/testing-library/package.json
- packages/testing-library/src/index.ts
- packages/testing-library/src/se-tools/display.ts
- packages/testing-library/src/se-tools/workflow.ts
- packages/testing-library/src/wallet/index.ts
- packages/testing-library/src/wallet/utils.ts
- packages/testing-library/tests/fixtures/bip32_ecdsa.json
- packages/testing-library/tests/fixtures/bip32_ed25519.json
- packages/testing-library/tests/index.spec.ts
- packages/testing-library/tsconfig.json
Publish `@coolwallet/testing-library` to enhance efficiency in writing tests.
> release(testing-library): publish @coolwallet/testing-library

- packages/coin-avaxc/package-lock.json
- packages/coin-evm/package.json
- packages/coin-evm/src/chain/fantom/index.ts
- packages/coin-evm/src/chain/fantom/token.ts
- packages/coin-evm/src/chain/index.ts
- packages/coin-evm/src/chain/velas/index.ts
- packages/coin-evm/src/chain/velas/token.ts
- packages/coin-evm/tools/chain.ts
- packages/coin-tester/src/components/coins/evm/index.tsx
> feat(evm): CW 7283 add FTM and VLX to EVM

- packages/coin-trx/src/config/tokenType.ts
https://tronscan.org/#/token20/TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8/code
> feat(TRC-20): Add USDC

- packages/coin-sol/package-lock.json
- packages/coin-sol/package.json
- packages/coin-sol/src/index.ts
- packages/coin-sol/src/utils/scriptUtil.ts
- packages/coin-sol/tests/index.spec.ts
- packages/coin-sol/tsconfig.json
- packages/coin-tester/package-lock.json
- packages/coin-tester/package.json
- packages/coin-tester/src/components/coins/sol/index.tsx
> feat(Solana): CW-7430 Unit test 

- package-lock.json
- packages/coin-iotx/package.json
> feat(IOTX): add overrides

- packages/coin-bsc/package.json
> Chore(BSC) CW-9447: Release new version

- packages/coin-tester/src/components/settings.tsx
- packages/core/package.json
- packages/core/src/apdu/execute/command.ts
- packages/core/src/apdu/execute/execute.ts
- packages/core/src/apdu/mcu/dfu.ts
- packages/core/src/apdu/mcu/types.ts
> feat(core) - add MCU version command

- packages/coin-aptos/package.json
- packages/coin-aptos/src/utils/index.ts
- packages/coin-tester/src/components/coins/aptos/index.tsx
- packages/coin-tester/src/components/coins/aptos/utils/api.ts
> feat(aptos):fix gas limit api error and update sdk for null input

- .github/workflows/assign_reviewers.yml
> feat(git):add auto assign

- packages/coin-evm/package.json
- packages/coin-evm/src/chain/goreli/index.ts
- packages/coin-evm/src/chain/goreli/token.ts
> feat(ETH): CW-10804 add ETH goerli chain

- packages/coin-evm/package.json
- packages/coin-evm/src/chain/index.ts
> feat(EVM): add export list

- packages/coin-evm/package.json
- packages/coin-evm/src/chain/goreli/index.ts
- packages/coin-tester/package.json
- packages/coin-tester/src/components/coins/evm/index.tsx
> feat(EVM): fix goreli signature error

- packages/coin-tester/src/components/coins/ada/txField.tsx
> [CW-12361] fix: coin-tester cardano withdrawal bug

- packages/coin-bch/package.json
- packages/coin-bch/src/utils/transactionUtil.ts
> feat(BCH): update bch script decode

- packages/coin-evm/package.json
- packages/coin-evm/src/chain/index.ts
- packages/coin-evm/src/chain/zkSync/index.ts
- packages/coin-evm/src/chain/zkSync/token.ts
- packages/coin-evm/tests/index.spec.ts
- packages/coin-evm/tools/chain.ts
- packages/coin-tester/src/components/coins/evm/index.tsx
- packages/coin-tester/src/components/settings.tsx
> feat(ZKS): CW-13116 add zks layer

- packages/coin-evm/package.json
- packages/coin-evm/src/chain/linea/index.ts
- packages/coin-evm/src/chain/linea/token.ts
> feat(LINEA): CW-17911 add linea chain

- packages/core/package.json
- packages/core/src/coin/ECDSA.ts
> feat(core): CW-18182 modify subArray to match react environment

- packages/coin-btc/package.json
- packages/coin-btc/src/utils/scriptUtil.ts
> feat(BTC): CW-18216 update change path

- packages/coin-btc/package.json
- packages/coin-btc/src/utils/scriptUtil.ts
> feat(BTC): CW-18216 fix change path issue

- packages/core/package.json
- packages/core/src/coin/ECDSA.ts
> feat(core): CW-18216 add reset method

- .github/workflows/assign_reviewers.yml
> feat(assign-reviewer): update auto assign team reviewer

- .github/workflows/assign_reviewers.yml
> feat(action): update reviewer config

- .github/workflows/assign_reviewers.yml
> feat(token): update auto assign reviewer

- packages/coin-btc/package.json
- packages/coin-btc/src/sign.ts
- packages/coin-btc/src/utils/transactionUtil.ts
> feat(BTC): CW-19180 add ecc lib import

- packages/coin-btc/package-lock.json
- packages/coin-btc/package.json
- packages/coin-btc/src/index.ts
- packages/coin-btc/src/utils/transactionUtil.ts
> feat(BTC): add p2tr address format judgemant

- packages/coin-evm/package.json
- packages/coin-evm/src/chain/dis/index.ts
- packages/coin-evm/src/chain/dis/token.ts
- packages/coin-evm/src/chain/index.ts
- packages/coin-evm/tools/chain.ts
> feat(ETH): CW-18698 add DIS chain

- packages/coin-ltc/package-lock.json
- packages/coin-ltc/package.json
- packages/coin-ltc/src/utils/bufferUtil.ts
- packages/coin-ltc/src/utils/transactionUtil.ts
> chore: remove unused package

- packages/coin-ltc/package.json
> chore: increase package version

- packages/coin-btc/package-lock.json
> feat(publish): update core dependency

- packages/coin-btc/package.json
- packages/coin-btc/src/sign.ts
- packages/core/package.json
- packages/core/src/transaction/txFlow.ts
- packages/core/src/transaction/txUtil.ts
- packages/core/src/transaction/type.ts
> feat(core/BTC): core 舊介面容舊

- packages/coin-btc/package.json
- packages/core/package.json
> chore(core/btc): update version

- packages/coin-btc/package-lock.json
> chore(btc): update version

- packages/coin-btc/package-lock.json
- packages/coin-btc/package.json
> feat(BTC): update core dependency in btc

- packages/coin-ada/package-lock.json
- packages/coin-ada/package.json
- packages/coin-ada/src/index.ts
> faet(ADA): CW-20013 update core dependency in Cardano

- packages/coin-ada/package-lock.json
- packages/coin-ada/package.json
- packages/coin-ada/src/index.ts
> feat(ADA): CW-20013 update cardano error

- packages/coin-sol/package.json
- packages/coin-sol/src/utils/signIn.ts
> fix: adjusting the order of arguments

- packages/core/package-lock.json
- packages/core/package.json
> chore(core): upgrade otaScript

- packages/coin-sol/package-lock.json
- packages/coin-sol/package.json
----
*Changes:*
This PR introduces new functionalities to our Wallet SDK to support the Solana blockchain, enhancing our SDK's versatility and utility for Solana developers and users. Specifically, the following Solana-specific functions have been added:
- `signTransaction`: This function allows users to sign Solana transactions. 
- `signMessage`: This function enables users to sign a given messages. 
- `signIn`: This function leverages SIWS to enable a simplified and secure authentication process.
*Checklist:*
> feat(sol): Release wallet support for smart contract and dApp signing capabilities.

- packages/coin-btc/package.json
- packages/coin-btc/src/utils/transactionUtil.ts
> feat(BTC): add p2wsh transaction

- packages/coin-btc/package-lock.json
- packages/coin-btc/package.json
- packages/coin-btc/src/utils/transactionUtil.ts
> feat(BTC): CW-20104 add p2wsh transaction

- packages/coin-sol/package.json
- packages/coin-sol/src/config/params.ts
- packages/coin-sol/src/config/types.ts
- packages/coin-sol/src/index.ts
- packages/coin-sol/src/message/index.ts
- packages/coin-sol/src/message/legacy.ts
- packages/coin-sol/src/message/v0.ts
- packages/coin-sol/src/message/versioned.ts
- packages/coin-sol/src/sign.ts
- packages/coin-sol/src/utils/Transaction.ts
- packages/coin-sol/src/utils/assert.ts
- packages/coin-sol/src/utils/commonLayout.ts
- packages/coin-sol/src/utils/publickey.ts
- packages/coin-sol/src/utils/rawTransaction.ts
- packages/coin-sol/src/utils/scriptUtil.ts
- packages/coin-sol/src/utils/shortvec-encoding.ts
- packages/coin-sol/src/utils/versionedTransaction.ts
> feat(sol): Support versioned transaction signing

- packages/coin-sol/package.json
> chore(sol): version fix-up

- packages/coin-sol/package-lock.json
- packages/coin-sol/package.json
> fix: correct beta version

- packages/coin-sol/package.json
- packages/coin-sol/src/config/params.ts
- packages/coin-sol/src/config/types.ts
- packages/coin-sol/src/index.ts
- packages/coin-sol/src/message/legacy.ts
- packages/coin-sol/src/message/versioned.ts
- packages/coin-sol/src/sign.ts
- packages/coin-sol/src/utils/Transaction.ts
- packages/coin-sol/src/utils/scriptUtil.ts
- packages/coin-sol/src/utils/versionedTransaction.ts
> feat(sol): CW-20080 Implemented signAllTransactions

- packages/coin-sol/package-lock.json
- packages/coin-sol/package.json
- packages/coin-sol/src/index.ts
- packages/coin-sol/src/sign.ts
- packages/coin-sol/src/utils/scriptUtil.ts
> fix: Refined the pre-action procedures for the card signing process

- packages/coin-sol/package-lock.json
- packages/coin-sol/package.json
> chore: Update package.sjon

- packages/coin-sol/package-lock.json
- packages/coin-sol/package.json
- packages/coin-sol/src/utils/rawTransaction.ts
> fix: Revise the order of instruction.accountKey

- packages/coin-sol/package-lock.json
- packages/coin-sol/package.json
> release(SOL): Added support for Token-2022 transfer signing

- packages/coin-sol/package-lock.json
- packages/coin-sol/package.json
- packages/coin-sol/src/index.ts
- packages/coin-sol/src/sign.ts
> feat(SOL): CW-20080 update sign all transaction return type

- packages/coin-doge/package-lock.json
- packages/coin-doge/package.json
> feat(DOGE): update doge release version

- .github/publish-action/dist/index.js
- packages/coin-doge/package-lock.json
- packages/coin-doge/package.json
> feat(DOGE): update publish index.js

- packages/coin-sol/package-lock.json
- packages/coin-sol/package.json
- packages/coin-sol/src/index.ts
> feat(SOL): CW-20414 fix signAllTransaction issue

- packages/coin-doge/package-lock.json
- packages/coin-doge/package.json
- packages/coin-doge/src/config/param.ts
- packages/coin-doge/src/utils/transactionUtil.ts
> feat(doge): CW-19851 add network parameter in payment parsing

- packages/coin-doge/package-lock.json
- packages/coin-doge/package.json
> feat(doge): update doge version

- packages/coin-doge/README.md
- packages/coin-doge/package-lock.json
- packages/coin-doge/package.json
- packages/coin-doge/src/index.ts
- packages/coin-doge/src/utils/transactionUtil.ts
Recovered Doge address is not correct. Fix it with configuring doge network params.
> fix(doge): fix fault recovered doge address

- packages/coin-doge/package.json
> 🔖 chore: upgrade doge to v1.0.2 from beta

- packages/coin-dot/src/utils/dotUtil.ts
- packages/core/src/apdu/wallet.ts
- packages/core/src/config/status/msg.ts
- packages/transport-react-native-ble/src/index.js
fix minor typos for docs
*Checklist:*
- [] Official docs or white paper.
> chore: fix typos

- packages/coin-sol/package-lock.json
- packages/coin-sol/package.json
- packages/coin-sol/src/utils/scriptUtil.ts
> feat(SOL): CW-20849 fix SPL custom token length issue

- packages/coin-sol/package-lock.json
- packages/coin-sol/package.json
- packages/coin-sol/src/utils/scriptUtil.ts
Fix sending failed if SPL token name is greater than 7 characters
> 🔖 chroe: upgrade sol to 1.1.9

- README.md
1. remove bnb from readme
2. add ada、doge、sol、xtz to readme
> 💬 chore: remove bnb from readme

- .github/publish-action/action.yml
> feat(publish): update publish action script

- .github/publish-action/action.yml
- .github/publish-action/dist/index.js
The previous PR of dist/index.js has been deleted and needs to be added back.
https://github.com/CoolBitX-Technology/coolwallet-sdk/pull/778/files
File creation process：
```
cd .github/publish-action
npm run build
```
> 📦️ [CW-19091] chore: update .github/publish-action/dist/index.js

- packages/coin-ton/README.md
- packages/coin-ton/package-lock.json
- packages/coin-ton/package.json
- packages/coin-ton/src/signTransferTransaction.ts
- packages/coin-ton/tests/index.spec.ts
- add coin-ton readme
- add coin-ton signTransaction testcase about memo
> [CW-19091] doc: add coin-ton readme and testcase (publish @coolwallet/ton: 1.0.0)

- packages/transport-jre-http/package.json
- packages/transport-jre-http/src/index.ts
update http-trasnport server port 8080 -> 9527
coolwallet-jcvm: https://github.com/CoolBitX-Technology/coolwallet-jcvm/pull/13/files
> 🔧 chore: update http-trasnport server port 8080 -> 9527 (publish @coolwallet/transport-jre-http 1.1.4)

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/index.ts
- **feat(core): export BleTransport in core**
- **chore(core): update version to 2.0.0-beta.4**
> ✨ feat(core): export BleTransport

- packages/transport-jre-http/src/index.ts
> chore: merge master into beta (update http trasnport server port 8080->9527)

- packages/transport-jre-http/package-lock.json
- packages/transport-jre-http/package.json
> chore(transport-jre-http): publish 2.0.0-beta.2

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/transport/index.ts
> feat(Transport): export CardType from Transport

- packages/transport-jre-http/package-lock.json
- packages/transport-jre-http/package.json
- packages/transport-jre-http/src/index.ts
- packages/transport-jre-http/src/transport.ts
> feat(http transport): update transport constructor to card type selectable

- packages/coin-ton/package-lock.json
- packages/coin-ton/package.json
- packages/coin-ton/src/config/tokenInfos.ts
- packages/transport-jre-http/package-lock.json
> feat(TON): Add official support for tokens: Tether USD, and Notcoin

- .github/workflows/auto_test.yml
> chore: update testcase jcvm port to 9527

- packages/coin-ton/package-lock.json
- packages/coin-ton/package.json
- packages/coin-ton/src/utils/checkParams.ts
- check address to make sure user cannot send asset to unexpected chain.
- release @coolwallet/ton:1.2.0
> feat(TON): check address's workchain and publish @coolwallet/ton:1.2.0

- packages/coin-ton/package-lock.json
- packages/coin-ton/package.json
- packages/coin-ton/src/utils/checkParams.ts
avoid crash when memo is null and publish @coolwallet/ton:1.2.1
> feat(TON): avoid crash when memo is null and publish @coolwallet/ton:1.2.1

- packages/coin-ton/package-lock.json
- packages/coin-ton/package.json
- packages/coin-ton/src/config/tokenInfos.ts
fix NOT token signature is mistake.
>  fix(TON): NOT token signature is mistake (@coolwallet/ton:1.2.2)

- packages/coin-ltc/package-lock.json
- packages/coin-ltc/package.json
- packages/coin-ltc/src/utils/transactionUtil.ts
> chore: remove debug log

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/config/index.ts
- packages/core/src/config/param.ts
> feat(key): CW-20890 add lite card key

- jest.config.ts
- packages/coin-sol/package-lock.json
- packages/coin-sol/package.json
- packages/coin-sol/src/utils/instructions.ts
- packages/coin-sol/src/utils/stringUtil.ts
refactor code for solana sending failure.
> refactor(SOL): refactor code for solana sending failure

- packages/coin-ada/package-lock.json
- packages/coin-ada/package.json
- packages/coin-ada/src/index.ts
> feat(ADA): CW-21407 fix cardano stake issue

- packages/core/package-lock.json
- packages/core/package.json
npm has core@2.x-beta. This PR tries to test whether 1.x beta can publish or not
> test: publish core 1.x beta

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/apdu/execute/command.ts
- packages/core/src/config/status/msg.ts
- packages/core/src/setting/backup.ts
> feat(backup): CW-21131 add export and import key

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/config/index.ts
> fix(core): call getSEPublicKey will throw Error: Unknown point format

- packages/core/src/config/status/pattern.ts
> fix(core): typescript compile error

- packages/coin-eth/package-lock.json
- packages/coin-eth/package.json
- packages/coin-eth/src/index.ts
- packages/coin-eth/src/sign.ts
- **chore: upgrade core to 2.x**
- **fix(eth): compile error**
- **chore(eth): upgrade coin-eth to 2.0.0-beta.1**
- **chore: run 'npm install'**
I have tested transfer ETH on CoolWallet App locally with this lib.
> chore(eth): CW-21101 CW-21172 CW-21510 upgrade coin-eth to v2

- packages/testing-library/package-lock.json
- packages/testing-library/package.json
> feat(testing-library): update core dependency to 2.0.0-beta.13

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/config/index.ts
> 🐛 fix(core): error `Unknown point format` above Pro SE 338

- README.md
> docs: add some supported coins into README.md

- packages/coin-eth/package-lock.json
- packages/coin-eth/package.json
- packages/coin-evm/package-lock.json
- packages/coin-evm/package.json
- packages/testing-library/package-lock.json
- packages/testing-library/package.json
- packages/transport-jre-http/package-lock.json
- packages/transport-jre-http/package.json
> chore(eth, evm, testing-library, transport-jre-http): upgrade @coolwallet/core to 2.0.0-beta.14

- .github/publish-action/dist/index.js
- .github/publish-action/index.ts
- packages/coin-kas/.babelrc
- packages/coin-kas/README.md
- packages/coin-kas/package-lock.json
- packages/coin-kas/package.json
- packages/coin-kas/src/config/param.ts
- packages/coin-kas/src/index.ts
- packages/coin-kas/src/utils/__test__/address.test.ts
- packages/coin-kas/src/utils/address.ts
- packages/coin-kas/src/utils/base32.ts
- packages/coin-kas/src/utils/checksum.ts
- packages/coin-kas/src/utils/convertBits.ts
- packages/coin-kas/src/utils/utils.ts
- packages/coin-kas/src/utils/validate.ts
- packages/coin-kas/tests/index.spec.ts
- packages/coin-kas/tsconfig.json
> [CW-21262] feat(kas): implement derive address

- packages/coin-ada/package-lock.json
- packages/coin-ada/package.json
> chore(coin-ada): CW-21548 upgrade core to 2.0

- packages/coin-bsc/package-lock.json
- packages/coin-bsc/package.json
- packages/coin-bsc/src/sign.ts
- **chore: install @coolwallet/core@^2.0.0-beta.12**
- **fix(bsc): fix compile error**
> chore(coin-bsc): CW-21514 upgrade coin-bsc to v2

- packages/coin-bsc/package.json
- packages/coin-bsc/tests/index.spec.ts
- test recover address 
- test sending BNB on BSC chain
> test(bsc): add bsc test cases

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/transaction/command.ts
- packages/core/src/transaction/flow.ts
next PR will adjust @coolwallet/coin-btc implementation and unit test
> feat(core): modify @coolwallet/core to support btc on lite

- packages/coin-btc/package-lock.json
- packages/coin-btc/package.json
- packages/coin-btc/src/sign.ts
- packages/coin-btc/src/utils/scriptUtil.ts
- packages/coin-btc/src/utils/versionUtil.ts
- packages/coin-btc/tests/index.spec.backup.ts
- packages/coin-btc/tests/index.spec.ts
upgrade @coolwallet/coin-btc to support btc on lite.
send taproot success: ✅ 
https://btcscan.org/tx/ce89a85aeeb2f6b5b5228b32e156e7e7d0befde82f67a184a25e34a71e5ea054
send custom segwit success: ✅ 
https://btcscan.org/tx/a3f2de86692919795ff7bd981689d35f8a2b0cadf1e9a04c008955e694df9cdd
Execute command `npm run 'test'` or `npm run 'test-lite'` to run test file index.spec.ts and passed the unit test. ✅
> feat(btc): support btc on lite

- packages/coin-kas/package.json
> 🐛 fix(kas): ci test issue

- packages/core/src/setting/backup.ts
- packages/core/tests/index.spec.ts
- packages/testing-library/src/se-tools/workflow.ts
> feat(test): CW-21471 create register devices test case

- packages/coin-trx/package-lock.json
- packages/coin-trx/package.json
- packages/coin-trx/src/index.ts
- packages/coin-trx/tests/index.spec.ts
- **feat: add TRX.getAddressFromAddressPublicKey**
- **chore(coin-trx): upgrade to v2.0.0-beta.1**
This method will be used by App from deriving address from address public key
> feat(coin-trx): add getAddressFromAddressPublicKey

- packages/coin-kas/package-lock.json
- packages/coin-kas/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/apdu/transaction.ts
1. 修正 hashKey undefined 仍會變成字串接在一起問題
2. format
3. 更新 core、kas 用到的 core 版本
原先用 jcvm 測試安裝 @core/^1.1.28-beta.1 的 BTC 跑測試會不過，
改安裝 local 修正的版本就過了
> fix(KAS): 修正 hash key undefined issue

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/apdu/ota/constants.ts
> fix(core): 修正 ota version 仍是 339 問題

- README.md
- packages/coin-kas/package-lock.json
- packages/coin-kas/package.json
- packages/core/package-lock.json
- packages/core/package.json
------------
**Summary:**
This pull request introduces a new package `@coolwallet/kas` for Icon (KAS) support and updates the version numbers of `@coolwallet/kas` and `@coolwallet/core` in various files. Additionally, it adjusts the package version number.
- Introduced `@coolwallet/kas` for Icon (KAS) support.
- Updated version numbers of `@coolwallet/kas` and `@coolwallet/core`.
- Package version number adjustment.
**Categorized Changes:**
**README.md:**
- Added a new line for `@coolwallet/kas` and updated its version number.
**packages/coin-kas:**
- Updated the version number of `@coolwallet/kas` and `@coolwallet/core` in package-lock.json, package.json.
**packages/core:**
- Updated the version number of `@coolwallet/core` in package-lock.json. …
> feat(kas、core): release core and kas

- packages/core/package-lock.json
- packages/core/package.json
as title
------------
**Summary**
The pull request contains updates to the package versions, specifically the `@coolwallet/core` package.
**Changes**
* Updated `@coolwallet/core` package version:
* Changed from `1.1.29-beta.0` to `1.1.29` in both `package-lock.json` and `package.json` files.
**Impact**
* Stable release of `@coolwallet/core` package is now being used.
**Files Changed**
* `package-lock.json`: updated `version` field for `@coolwallet/core`.
* `package.json`: updated `version` field for `@coolwallet/core`.
**Categories**
* Package versions
* File updates
* Dependency management
* Release type (beta to stable) 
<h6>To turn off PR summary, please visit <a href="https://app.typoapp.io/settings/dev-analytics/notification?tab=codeHealth">Notification …
> 🔖 chore: update @coolwallet/core version to 1.1.29

- .github/workflows/beta-publish.yml
------------
**Summary**
This pull request updates `actions/checkout` and `actions/setup-node` versions in `beta-publish.yml` to ensure compatibility with their latest versions (v4 for both).
**Key Points**
1. Updates `actions/checkout` from v2 to v4.
2. Updates `actions/setup-node` from v1 to v4.
3. Intended to ensure compatibility with the latest versions. 
> chore: modify for new action version

- packages/coin-bsc/package-lock.json
- packages/coin-bsc/package.json
- packages/coin-bsc/src/index.ts
- packages/coin-bsc/tests/index.spec.ts
> 🐛 fix(bsc): sign typed data error on lite

- packages/coin-eth/package-lock.json
- packages/coin-eth/package.json
- packages/coin-eth/src/index.ts
> 🐛 fix(eth): sign typed data error on lite

- packages/coin-bsc/package-lock.json
- packages/coin-bsc/package.json
----
*Checklist:*
------------
**Summary**
Upgraded `@coolwallet/bsc` to version `2.0.0-beta.3` in `package-lock.json` and `package.json`.
**Key Points**
* Updated `@coolwallet/bsc` version in `package-lock.json` and `package.json`.
* New version is `2.0.0-beta.3`. 
> chore(bsc): updata bsc version for trying publish to npm

- packages/core/src/apdu/ota/ota.ts
----
*Checklist:*
------------
**Summary**
This pull request introduces new functions for SE version handling, applet existence check, progress tracking, and data backup/recovery in the `ota.ts` file. It also refactors and simplifies existing functions using new approaches.
**Key Points**
* Introduces `safeGetSEVersion`, `safeCheckMainAppletExists`, `getProgressNums`, `performBackupRegisterData`, and `performRecoverBackupData` functions
* Refactors `checkUpdate` function and introduces `enge` function
* Simplifies code using `performApiChallenge` function and adds backup data recovery step. 
<h6>To turn off PR summary, please …
> ♻️ refactor(core): adjust updateSE function code to improve readability

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/apdu/ota/index.ts
> chore(core): export getMainAppletAid, getNewSeVersion method from constant

- .github/workflows/auto_test_lite.yml
----
*Checklist:*
------------
**Summary**
This pull request updates `auto_test_lite.yml` to use `npm run ci-test-lite` instead of `npm run ci-test` for testing a coin, introducing a lighter test version.
**Key Points**
* `auto_test_lite.yml` workflow file is modified.
* `npm run ci-test` is replaced with `npm run ci-test-lite` for specific coin testing.
* `npm run ci-test-lite` likely runs a lighter version or a subset of tests. 
> fix(action): update lite card auto test script

- packages/coin-doge/package-lock.json
- packages/coin-doge/package.json
- packages/coin-doge/src/sign.ts
- packages/coin-doge/src/utils/scriptUtil.ts
- packages/coin-doge/tests/index.spec.ts
- packages/testing-library/package-lock.json
> feat: support doge on lite in sdk

- scripts/run-all-test.sh
----
*Checklist:*
------------
**Summary**
Introduced new script "scripts/run-all-test.sh" for running tests in multiple scopes using Lerna. Set up test environments and executed bootstrap, build, and test commands.
**Key Points**
* Introduced new script for running tests across multiple scopes
* Utilized Lerna for test setup and execution
* Executed bootstrap, build, and test commands for each scope 
> 🔨 chore: add script to run all test case

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/crypto/signature.ts
as title
----
*Checklist:*
------------
**Summary**
This pull request updates the `@coolwallet/core` package version and adds an optional parameter to a function.
**Key Points**
* Updates `@coolwallet/core` package version from `1.1.30-beta.0` to `1.1.30-beta.1`
* Modifies `getCanonicalSignature` function in `crypto/signature.ts` to handle optional `s32` parameter. 
> 🐛 fix: eth test failed

- packages/coin-eth/package-lock.json
- packages/coin-eth/package.json
----
*Checklist:*
------------
**Summary:**
This pull request updates `@coolwallet/eth` version to `1.1.22.beta.1` and `@coolwallet/core` version to `1.1.30-beta.1`.
1. `@coolwallet/eth` version updated in `package-lock.json` and `package.json`.
2. New beta version `1.1.30-beta.1` for `@coolwallet/core` dependencies and peerDependencies. 
> 🐛 fix: upgrade eth dependencies core version

- .gitignore
- package-lock.json
- package.json
- packages/coin-ada/package.json
- packages/coin-atom/package.json
- packages/coin-atom/tests/teansactionUtil.test.ts
- packages/coin-atom/tests/txProtobuf.test.ts
- packages/coin-bsc/package.json
- packages/coin-btc/package.json
- packages/coin-btc/tests/index.spec.ts
- packages/coin-cosmos/package.json
- packages/coin-dot/package.json
- packages/coin-dot/tests/index.spec.ts
- packages/coin-eth/package.json
- packages/coin-evm/package.json
- packages/coin-kas/package.json
- packages/coin-kas/src/utils/__test__/address.test.ts
- packages/coin-kas/src/utils/__test__/hash.test.ts
- packages/coin-kas/src/utils/__test__/validate.test.ts
- packages/coin-terra/package.json
- packages/coin-ton/package.json
- packages/coin-ton/src/utils/__test__/addressUtils.test.ts
- packages/coin-ton/src/utils/__test__/scriptUtils.test.ts
- packages/coin-ton/src/utils/__test__/transactionUtils.test.ts
- packages/coin-xtz/package.json
- packages/core/package.json
- scripts/run-all-test-report.sh
- scripts/run-all-test.sh
1. 在 package.json 增加一個 ci-test-report 的 script 在測試過程中可以產出 junit 的報告
2. 修改部分 .test.ts 檔案裡面的 describe 讓報告更容易聚焦是哪個幣種的測試結果
3. 詳細內容可參考 `scripts/run-all-test-report.sh` 的說明
4. 執行全部 testcase 約需花費 11 分鐘
----
*Checklist:*
> 🔨 chore: add script to run all testcase and generate report

- packages/coin-dot/package-lock.json
- packages/coin-dot/package.json
- packages/coin-eth/package-lock.json
- packages/coin-eth/package.json
----
*Checklist:*
------------
**Summary**
Updates package "@coolwallet/dot" version from "1.1.8.beta.0" to "1.1.8-beta.0" in package-lock.json and package.json.
**Key Points**
1. Version number changed in package files.
2. New version is "1.1.8-beta.0".
3. Affects package-lock.json and package.json only. 
> 🐛 fix: dot wrong version

- .github/workflows/auto_test_lite.yml
- packages/coin-eth/package-lock.json
- packages/coin-eth/package.json
- packages/coin-eth/src/index.ts
- packages/coin-eth/tests/index.spec.ts
----
*Checklist:*
------------
**Summary**
Upgraded `@coolwallet/eth` package from version `2.0.0-beta.3` to `2.0.0-beta.4` in `package-lock.json` and `package.json` files.
**Key Points**
* Updated `@coolwallet/eth` package version in `package-lock.json` and `package.json` files.
* Upgraded from `2.0.0-beta.3` to `2.0.0-beta.4`. 
> feat(ci): trigger auto test

- packages/coin-evm/package-lock.json
- packages/coin-evm/package.json
- packages/coin-evm/src/chain/customEvm/index.ts
- packages/coin-evm/src/chain/types.ts
- packages/coin-evm/src/index.ts
- packages/coin-evm/tests/index.spec.ts
- **feat: new Evm module with chainId**
- **feat: recover address for custom evm**
------------
**Summary**
This pull request updates package versions, introduces a new class, and adds tests.
**Key Points**
1. Updates `@coolwallet/evm` package versions and introduces `CustomEvm` class.
2. Changes creation of coin objects to use `id` property and adds 'Scroll' coin.
3. Adds test for getting address 0 using wallet and API methods. 
> ✨ [CW-20519][CW-20796] feat: implement CustomEvm recover address

- packages/coin-evm/package-lock.json
- packages/coin-evm/package.json
- packages/coin-evm/src/chain/index.ts
- packages/coin-evm/tests/index.spec.ts
- **fix: use custom evm script to fix Aurora signature failed**
- **chore: update coin-evm version to 1.1.0-beta.2**
------------
**Summary**
This pull request updates package versions to `1.1.0-beta.2` and introduces a new constant `customCoinAurora` for Aurora chain.
**Key Points**
* Updates package versions in `package-lock.json` and `package.json`
* Introduces new constant `customCoinAurora` for Aurora chain, commented out in production. 
> fix(coin-evm): use Custom EVM script for Aurora

- .gitignore
- scripts/update-core-version.sh
script 執行步驟如下：
1. 將各幣種 npm info 輸出到 JSON 文件 package-info.json
2. 找出已經更新過的幣種加到 IGNORE_SCOPES 內
3. 組出要執行的 command
4. 執行 lerna command & npm version patch
----
*Checklist:*
------------
**Summary:**
This pull request updates the `.gitignore` file to ignore `package-info.json` and adds a new script `scripts/update-core-version.sh` for installing the latest `@coolwallet/core` version.
1. `.gitignore` updated to ignore `package-info.json`.
2. New script `scripts/update-core-version.sh` added for installing latest `@coolwallet/core`. 
<h6>To turn off PR summary, please visit <a …
> 🔨 chore: add script to update core version

- scripts/update-core-version.sh
as title
*Checklist:*
------------
**Summary**
This pull request refactors `scripts/update-core-version.sh` by removing redundant comments and adjusting the `npm version` command sequence.
**Key Points**
1. Eliminated superfluous comments.
2. Reordered `npm version patch` execution for correct branch merging. 
> ✨ chore: script mark version patch

- packages/coin-eth/package-lock.json
- packages/coin-eth/package.json
- packages/coin-eth/tools/token.ts
- packages/coin-evm/package-lock.json
- packages/coin-evm/package.json
- packages/coin-evm/tools/token.ts
- packages/coin-sol/package-lock.json
- packages/coin-sol/package.json
as title
ref: https://github.com/CoolBitX-Technology/coolwallet-sdk/pull/911
- **chore: upgrade eth, evm and sol to formal version**
- **chore: execute `npm install` for the packages**
- **chore(eth): add script to generate token hex**
------------
**Summary:**
This pull request updates packages and adds new dependencies, including "core-js" and related packages, for improved data handling and compatibility.
1. Adds "core-js" version 3.39.0 and related packages.
2. Updates engines requirement to Node.js >= 0.4 for some packages.
3. Includes SHA-512 checksums for verification. 
> chore: upgrade packages to formal version and add `npm run list:token` script in coin-eth

- packages/coin-ton/package-lock.json
- packages/coin-ton/package.json
- packages/coin-trx/package-lock.json
- packages/coin-trx/package.json
Continuation of this PR:
- #914 
----
*Checklist:*
> chore(ton, tron): update SDK version in package.json

- README.md
- packages/coin-sui/package-lock.json
- packages/coin-sui/package.json
- packages/coin-sui/src/config/types.ts
- packages/coin-sui/src/index.ts
- packages/coin-sui/src/utils/checkParams.ts
- packages/coin-sui/src/utils/scriptUtil.ts
- packages/coin-sui/tests/index.spec.ts
- packages/coin-sui/tests/testData.ts
------------
**Summary:**
This pull request simplifies the handling of payment data, exports additional types and utilities, and modifies tests for Sui cryptocurrency support in the Coolwallet project.
1. Simplified payment handling and updated imports.
2. Exported new types and utilities.
3. Modified tests for Sui cryptocurrency support. 
> fix: export types and refactor tests

- packages/coin-dot/package-lock.json
- packages/coin-dot/package.json
- packages/coin-dot/src/sign.ts
- packages/coin-dot/src/utils/transactionUtil.ts
- packages/transport-jre-http/tsconfig.json
------------
**Summary:**
- Multiple pull requests with dependency updates and integrity checks.
- Changes include new versions of "@types" packages, SHA-512 integrities, and dependency removals/additions.
1. Dependency updates for several packages, including "@types" and core libraries.
2. Integrity checks and SHA-512 hashes added to some packages.
3. Dependency removal and addition, such as "@noble/secp256k1" and "@polkadot/keyring". 
> [CW-23118] feat(dot): support on lite in sdk

- packages/coin-zen/package.json
- packages/coin-zen/tests/index.spec.ts
- packages/coin-zen/tsconfig.json
- **test: add zen test case**
- **test: add zen testdata**
- **test: skip failed test case in ZEN**
------------
**Overview**
This PR adds a test suite for the ZEN coin SDK, including test data and scripts for running tests. One failing test case has been temporarily skipped.
- New test suite in `packages/coin-zen/tests/index.spec.ts`.
- Test data for ZEN transactions added.
- `package.json` updated with test scripts.
- `tsconfig.json` updated to include test files.
- One failing test case skipped.
Address the skipped test case before merging.  Review the test coverage to ensure it's sufficient.
<h6>To turn off PR summary, please visit <a href="https://app.typoapp.io/settings/dev-analytics/notification?tab=codeHealth">Notification …
> test(coin-zen): [CW-23417] add zen failing test case

- packages/coin-xrp/package-lock.json
- packages/coin-xrp/package.json
- packages/coin-xrp/src/config/types.ts
- packages/coin-xrp/src/sign.ts
- packages/coin-xrp/src/tests/index.spec.ts
- packages/coin-xrp/src/utils/scriptUtil.ts
- packages/coin-xrp/src/utils/stringUtil.ts
- packages/coin-xrp/tsconfig.json
------------
**Overview**
This PR adds XRP support on the CoolWallet Lite in the SDK. It updates dependencies, modifies transaction signing logic, and includes test cases.
- Updates `@coolwallet/core` dependency to `^2.0.0-beta.18` and the package version to `^2.0.0-beta.0`.
- Modifies `signPayment` to use `getSingleSignatureFromCoolWalletV2` and `DER` signature type.
- Makes `SigningPubKey` and `Account` optional in `Payment` type, adding checks for them during signing.
- Adds `test-lite` script and test cases for address derivation and transaction signing.
Ready for merge after review and CI checks pass.  Ensure the new test cases provide adequate coverage for the Lite card functionality.
<h6>To turn off PR summary, please visit …
> feat(xrp): support on lite in sdk

- packages/coin-xrp/package-lock.json
- packages/coin-xrp/package.json
------------
**Overview**
This PR updates the `@coolwallet/xrp` package to version 2.0.0-beta.1, primarily adding CI test scripts and updating the dependency on `@coolwallet/core` to version 2.0.0-beta.19.
- Added `ci-test` and `ci-test-lite` scripts to package.json for running tests in a production environment.
- Updated the `@coolwallet/core` dependency to 2.0.0-beta.19.
- Bumped the package version to 2.0.0-beta.1.
Ready to merge after verifying the CI tests pass successfully.
> feat: 加入 ci-test & 更新 core 版本

- .github/publish-action/dist/index.js
- .github/publish-action/utils.ts
讓部署錯誤能顯示出來，原先的部署因為編譯導致的失敗不會顯示任何資訊
> feat: add publish action error log

- packages/coin-sui/package-lock.json
- packages/coin-sui/package.json
- packages/coin-sui/src/sign.ts
- packages/coin-sui/tests/index.spec.ts
> ✨  [CW-22935] feat(sui): support sui on lite

- packages/coin-bch/package-lock.json
- packages/coin-bch/package.json
- packages/coin-bch/src/sign.ts
- packages/coin-bch/src/utils/scriptUtil.ts
- packages/coin-bch/tests/index.spec.ts
Local build tests on CoolWallet Go:
- recover BCH ✅ 
- add new address ✅ 
----
*Checklist:*
------------
**Overview**
This PR updates the BCH SDK to support CoolWallet Go, upgrading the `@coolwallet/core` dependency to `2.0.0-beta.19` and changing the signing flow to use `getSignaturesFromCoolWalletV2`. It also modifies script execution commands to use the new `tx.command` methods from the updated core library.
- Bumps `@coolwallet/core` version to `2.0.0-beta.19`.
- Updates signing flow to use `getSignaturesFromCoolWalletV2` and sets signature type to DER.
- Replaces `apdu.tx` script commands with `tx.command` …
> ✨ [CW-21845] feat(bch): support bch on CoolWallet Go 

- packages/coin-ton/package-lock.json
- packages/coin-ton/package.json
- packages/coin-ton/src/signTransferTokenTransaction.ts
- packages/coin-ton/src/signTransferTransaction.ts
> ✨  [CW-21898] feat(ton): support TON on lite

- packages/testing-library/package-lock.json
- packages/testing-library/package.json
----
*Checklist:*
------------
**Overview**
This PR upgrades the `@coolwallet/core` dependency in the `@coolwallet/testing-library` package from version `2.0.0-beta.14` to `2.0.0-beta.20`. This upgrade enables support for creating Cardano seeds on CoolWallet Go.  The package version is bumped to 2.0.0-beta.4.
- Updated the `@coolwallet/core` dependency to `2.0.0-beta.20` in both `package.json` and `package-lock.json`.
- Incremented the `@coolwallet/testing-library` version to `2.0.0-beta.4`.
Ready for deployment. This is a dependency update with a clear purpose and minimal changes, reducing the …
> feat(testing-library): upgrade @coolwallet/core to support creating cardano seed on coolwallet go

- packages/coin-ada/package-lock.json
- packages/coin-ada/package.json
- packages/coin-ada/src/index.ts
----
*Checklist:*
------------
**Overview**
This PR adds support for Cardano on CoolWallet Go, updating the `@coolwallet/ada` package to version `2.0.0-beta.0` and introducing compatibility with the new `@coolwallet/core` beta version. The changes include updates to transaction signing logic and the handling of signatures, differentiating between CoolWallet Pro and CoolWallet Lite.
- Updated `@coolwallet/ada` and `@coolwallet/core` dependencies to beta versions.
- Refactored transaction signing process using updated `@coolwallet/core` API.
- Implemented separate signature handling for CoolWallet Pro (decryption) …
> ✨ [CW-21834] feat(ada): support cardano on coolwallet go

- packages/coin-sol/package-lock.json
- packages/coin-sol/package.json
- packages/coin-sol/src/sign.ts
- packages/coin-sol/src/utils/scriptUtil.ts
- packages/coin-sol/tests/index.spec.ts
- packages/coin-sol/tsconfig.json
> ✨ [CW-21881] feat: support sol on go

- packages/coin-sol/jest.config.ts
- packages/coin-sol/package-lock.json
- packages/coin-sol/package.json
- packages/coin-sol/tests/index.spec.ts
------------
**Overview**
This PR fixes failing tests in the `coin-sol` package. It updates dependencies, modifies the Jest configuration, and corrects the test logic to align with the latest Solana library changes.  The changes also address a test file inclusion issue.
- Added a Jest configuration file (`jest.config.ts`) to the `coin-sol` package, resolving issues with test file discovery and setup.
- Updated Solana dependencies, including `@solana/spl-token` and `@solana/web3.js`, to newer versions.
- Modified test cases in `index.spec.ts` to reflect changes in the updated Solana libraries, specifically addressing changes related to token transfers and account creation.
- Corrected test logic to handle asynchronous operations and promises …
> fix(sol): 修正測試不過的問題 - [CW-23595]

- packages/coin-xlm/package-lock.json
- packages/coin-xlm/package.json
- packages/coin-xlm/tests/index.spec.ts
> ✨  [CW-23635][CW-23641] feat(xlm): support KAU and KAG on go

- packages/coin-etc/package-lock.json
- packages/coin-etc/package.json
- packages/coin-etc/src/index.ts
- packages/coin-etc/tests/index.spec.ts
- packages/coin-etc/tsconfig.json
------------
**Overview**
This PR adds support for ETC on CoolWallet GO by updating the `@coolwallet/etc` package. It upgrades dependencies, including `@coolwallet/core`, introduces unit tests, and modifies the signing process to support both CoolWallet Pro and CoolWallet Lite.
- Bumps `@coolwallet/etc` version to `2.0.0-beta.0` and `@coolwallet/core` to `2.0.0-beta.19`.
- Updates the `signTransaction` function to handle both Pro and Lite card types.
- Adds unit tests for address derivation and transaction signing.
- Updates build scripts and adds CI test commands.
Ready for deployment. The changes are well-structured, include comprehensive unit tests, and address compatibility for different card types, enhancing the project's …
> [CW-23648] feat: support ETC on go

- packages/coin-aptos/package-lock.json
- packages/coin-aptos/package.json
- packages/coin-aptos/src/config/types.ts
- packages/coin-aptos/src/index.ts
- packages/coin-aptos/src/utils/index.ts
- packages/coin-aptos/tests/index.spec.ts
------------
**Overview**
This PR adds support for Aptos on the CoolWallet Go. It updates dependencies, adds test scripts, modifies the signing process to support both CoolWallet Pro and Lite, and includes unit tests.
- Bumps `@coolwallet/core` dependency to `2.0.0-beta.20`.
- Updates Aptos SDK version to `2.0.0-beta.0`.
- Adds unit tests for address derivation and transaction signing.
- Modifies the signing flow to handle both CoolWallet Pro and Lite.
- Updates the `signTransaction` function to use the new `@coolwallet/core` API.
Not deployment ready. While the changes address Aptos support and introduce necessary updates, the following improvements are needed:
- Expand test coverage to include edge cases and error scenarios. …
> feat(aptos): support apto on go

- packages/coin-ada/package-lock.json
- packages/coin-ada/package.json
------------
**Overview**
This PR updates the `@coolwallet/ada` package version from `2.0.0-beta.0` to `2.0.0-beta.1`.  It modifies both `package.json` and `package-lock.json` to reflect this change.  No code changes are included.
- Package version bumped to 2.0.0-beta.1 in both `package.json` and `package-lock.json`.
Not deployment ready. While this PR only involves version bumps, the lack of context around the changes makes it difficult to assess production readiness. Please provide details on the changes introduced in version 2.0.0-beta.1, including any potential impact on functionality, performance, or security.  A changelog entry or release notes would be helpful.
<h6>To turn off PR summary, please visit <a …
> chore(ada): support new tx type on go

- packages/coin-cro/tsconfig.json
----
*Checklist:*
------------
**Overview**
This PR updates the `tsconfig.json` file in the `coin-cro` package to include an `include` property. This change explicitly specifies that the TypeScript compiler should only process files within the `src` directory.
- Added an `include` property with the value `["src/**/*"]` to the `tsconfig.json` file.
Deployment ready. This simple change improves the build process by explicitly defining the source files to be included, promoting better code organization and potentially improving build times.
<h6>To turn off PR summary, please visit <a …
> feat(cro): update tsconfig

- packages/coin-icx/package-lock.json
- packages/coin-icx/package.json
- packages/coin-icx/src/config/params.ts
- packages/coin-icx/src/sign.ts
- packages/coin-icx/src/utils/scriptUtil.ts
- packages/coin-icx/src/utils/stringUtil.ts
- packages/coin-icx/src/utils/transactionUtil.ts
----
*Checklist:*
------------
**Overview**
This PR updates the `@coolwallet/icx` package to be compatible with `@coolwallet/core` version 2.0. It includes dependency updates, code refactoring for compatibility, and removal of peer dependencies.  The changes prepare the ICX coin package for use with the updated core library.
- Updated `@coolwallet/core` dependency to `^2.0.0-beta.20`.
- Removed peer dependency on `@coolwallet/core`.
- Refactored transaction signing flow to use `getSingleSignatureFromCoolWalletV2` and `Canonical` signature type.
- Updated `package.json` scripts for testing.
- Minor code cleanup and …
> feat(ICX): CW-23718 update to fit core v2.0

- packages/coin-sol/package-lock.json
- packages/coin-sol/package.json
> chore(sol): update solana/buffer-layout version to 4.0.0

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/tests/index.spec.ts
----
*Checklist:*
------------
**Overview**
This PR adds tests for the OTA (Over-the-Air firmware update) flow, specifically focusing on backing up and recovering register data.  It covers scenarios for successful backup and recovery, handling cases with no backup data, and ensuring the process works even with an unrecognized appId.
- Added test cases for `backupRegisterData`, `deleteBackupRegisterData`, and `recoverSeed` functions.
- Implemented tests to verify backup status using `checkBackupStatus`.
- Included scenarios for handling reset card operations and verifying wallet creation status.
- Added tests to …
> feat(core): CW-24146 upgrade core to 2.0.0-beta.24 to fix ota flow

- packages/core/src/apdu/ota/ota.ts
------------
**Overview**
This PR modifies the OTA update process to preserve backup data instead of deleting it. This change ensures that user data is retained during updates, preventing potential data loss.
- Removed the call to `deleteBackupRegisterData` during the OTA process.
- Added checks to prevent redundant backups if a backup already exists or if a wallet hasn't been created.
- Removed unused import `common` from `../..`.
Ready for deployment. This PR improves data safety during OTA updates by preserving backups. The changes are well-targeted and follow best practices.
<h6>To turn off PR summary, please visit <a href="https://app.typoapp.io/settings/notification?tab=codeHealth">Notification settings</a>.</h6>
> feat: [CW-24146] do not delete backup

- packages/core/package-lock.json
- packages/core/package.json
> chore: upgrade core to 2.0.0 official

- package-lock.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/coin/ECDSA.ts
- packages/core/src/coin/config/params.ts
- packages/core/src/coin/config/types.ts
- packages/core/src/coin/index.ts
- packages/core/src/coin/sign.ts
- packages/core/tests/coin/index.spec.ts
> feat: add sign ecdsa method - [CW-24311]

- packages/coin-evm/package-lock.json
- packages/coin-evm/package.json
- packages/coin-evm/src/index.ts
----
*Checklist:*
------------
**Overview**
This PR exports additional types and methods from the `@coolwallet/evm` package, specifically from the `transaction/types`, `utils/signature`, and `utils/rawTransaction` modules.  It also updates the package version to `2.0.1-beta.1`.
- Exported types from `./transaction/types`.
- Exported methods from `./utils/signature` and `./utils/rawTransaction`.
- Updated package version in `package.json` and `package-lock.json`.
Ready for deployment. This is a straightforward export of existing functionalities, minimizing risk.  The change enhances developer …
> refactor(evm): export some type and methods from @coolwallet/evm

- packages/coin-evm/tests/index.spec.ts
- packages/core/src/coin/config/types.ts
- packages/core/tests/coin/index.spec.ts
fix erros:
```
> @coolwallet/core@2.0.3-beta.1 build
> del-cli lib; npm run build:types; npm run build:ts
> @coolwallet/core@2.0.3-beta.1 build:types
> tsc --emitDeclarationOnly
src/coin/sign.ts:34:33 - error TS2345: Argument of type 'import("/Users/brian.yeh/Code/CoolBitX/coolwallet-sdk/node_modules/@coolwallet/core/lib/transport/index").default' is not assignable to parameter of type 'import("/Users/brian.yeh/Code/CoolBitX/coolwallet-sdk/packages/core/src/transport/index").default'.
34     await tx.command.sendScript(transport, script);
~~~~~~~~~
src/coin/sign.ts:39:37 - error TS2345: Argument of type 'import("/Users/brian.yeh/Code/CoolBitX/coolwallet-sdk/node_modules/@coolwallet/core/lib/transport/index").default' is not assignable to parameter of type …
```
> fix(core): fix `npm run build` failed

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/device/ble/PeripheralRequest.ts
- packages/core/src/transport/index.ts
- **fix(core): fix npm run build failed**
- **fix(core): Pro running Go test cases**
- **fix(coin-evm): test case error**
- **refactor: remove useless guard**
- **chore: add options to control logs of PeripheralRequest**
- **chore: bump version to 2.0.3-beta.2**
------------
**Overview:**
This PR adds logging control to `PeripheralRequest` in the `@coolwallet/core` package, allowing developers to enable or disable logs related to peripheral communication.  The version is bumped to 2.0.3-beta.2.
- Introduced a new `enablePeripheralLogs` option in the `PeripheralRequest` constructor and `BleTransport`.
- Added a `debugLog` method to `PeripheralRequest` that conditionally logs messages based on the `enablePeripheralLogs` flag.
- Replaced existing …
> chore(core): add logs control of PeripheralRequest

- packages/core/CHANGELOG.md
----
*Checklist:*
------------
**Overview**
This PR updates the changelog for the `core` package with two new entries: adding hooks to BleTransport and fixing the `cardInfo.cardanoSeed` type.  It also adds the PR number to existing changelog entries.
- Added a changelog entry for adding hooks to BleTransport (PR #1010).
- Added a changelog entry for fixing the `cardInfo.cardanoSeed` type (PR #1014).
- Added PR numbers to existing changelog entries for improved traceability.
Ready for deployment. This is a simple changelog update and introduces no code changes.
| Category    | Lines Changed | …
> docs(core): update packages/core/CHANGELOG.md 

- README.md
----
*Checklist:*
------------
**Overview:**
This PR updates the README to include instructions for CoolWallet Go (NFC) and improves the overall clarity of the documentation. It adds a new section for React Native NFC transport, updates examples for connecting to CoolWallet, and clarifies the registration process.
- Added `@coolwallet/transport-react-native-nfc` to the Transport section.
- Updated Examples section to include Web BLE, React Native BLE, and React Native NFC connection methods.
- Added `cardId` retrieval for React Native examples.
- Clarified the purpose of `transport`, `SEPublicKey`, and …
> feat(README): CW-24960 update README

- packages/coin-evm/package-lock.json
- packages/coin-evm/package.json
----
*Checklist:*
------------
**Overview**
This PR updates the version of the `@coolwallet/evm` package from its beta (`2.0.3-beta.0`) to its stable release (`2.0.3`).
- The `version` field in `packages/coin-evm/package.json` was updated to `2.0.3`.
- The corresponding `version` field in `packages/coin-evm/package-lock.json` was also updated to `2.0.3`.
ready for deployment. This change is a simple version bump, marking the package as stable without introducing any functional code changes.
| Category    | Lines Changed |
|-------------|---------------|
| Rework      | 3 (100.0%)    |
| Total …
> chore(evm): update version from 2.0.3-beta.0 to 2.0.3

- packages/coin-atom/package.json
- packages/coin-ltc/package.json
- packages/coin-sol/package.json
- packages/coin-xlm/package.json
----
*Checklist:*
------------
**Overview**
This PR standardizes and adds the `ci-test-report` script to several `coin` packages, specifically `atom`, `ltc`, `sol`, and `xlm`. The aim is to ensure consistent test reporting within the continuous integration pipeline for these components.
- Modified `packages/coin-atom/package.json` to update the `ci-test-report` script to use `jest` with `jest-junit` for reporting.
- Added the `ci-test-report` script to `packages/coin-ltc/package.json`, `packages/coin-sol/package.json`, and `packages/coin-xlm/package.json`, also configuring it to use `jest` and `jest-junit`. …
> feat(script): add missing scripts
